M48
; DRILL file {KiCad 9.0.0} date 2025-04-23T14:37:59+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-23T14:37:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X143.67Y-27.5
X143.67Y-65.5
X163.67Y-27.5
X163.67Y-65.5
M30
