M48
; DRILL file {KiCad 9.0.0} date 2025-04-01T20:46:00+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-01T20:46:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X74.0Y-50.7
X74.0Y-88.7
X94.0Y-50.7
X94.0Y-88.7
M30
