vt100.binary: *.spin openspin
	./openspin -b -u vt100.spin

openspin:
	wget --user-agent="Mozilla/5.0" -S -L https://www.maccasoft.com/wp-content/downloads/openspin_1_00_81-linux-x86_64.tar.gz
	tar -xvzf openspin_1_00_81-linux-x86_64.tar.gz
	rm -v openspin_1_00_81-linux-x86_64.tar.gz
