name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make cc65 libtclap-dev

      - name: Build Operating System
        run: |
          cd src/bcos
          make
      
      - name: Build TINY ROM
        run: |
          cd src/tinyrom
          make

      - name: Build programs
        run: |
          cd programs
          make

      - name: Build Emulator
        run: |
          cd emulator
          mkdir build && cd build
          cmake ../src
          make -j