name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make cc65 libtclap-dev git

      - name: Build Operating System
        run: |
          cd src/bcos
          make
      
      - name: Build TINY ROM
        run: |
          cd src/tinyrom
          make

      - name: Build MINI ROM
        run: |
          cd src/minirom
          make

      - name: Build programs
        run: |
          cd programs
          make

      - name: Build Emulator
        run: |
          cd emulator
          mkdir build && cd build
          cmake ../src
          make -j
      
      - name: Update tinyrom release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: tinyrom-latest
          name: Latest TinyROM Build
          files: |
            src/tinyrom/tinyrom.bin
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
